name: FlashEvents
version: '${project.version}'
main: me.naphy.flashevents.FlashEvents
api-version: 1.19
commands:
  flashevents:
    description: Main plugin command.
    usage: /<command> <args>
  flasheventssecret:
    usage: /<command> <args>